from tkinter import *
from tkinter import messagebox, colorchooser, font

loop = True
cookies = 0
cps = 0
current_row = 3 # starting row for cps buttons
prices = []
button_n = 0

base_price = 10
multi_cps = 1
multi_price = 1


def update_cookie_ammount():
    cookie_ammount.config(text=f"cookies: {round(cookies)}")

def get_cps():
    global cookies
    cookies += cps/30  #Divide number of cookies generated by 30
    update_cookie_ammount()
    window.after(33, get_cps)  #Call get_cps each 33 milliseconds (30 frames per second)
    check_for_new_button()

def get_cookie():
    global cookies
    cookies += 1
    update_cookie_ammount()

def upgrade_cps(ammount, text, current_button):
    global cps
    global cookies
    global prices

    print(current_button)
    
    if cookies < prices[current_button]:
        text.config(fg="#FF0000")
    else:
        cps+=ammount
        cookies-=prices[current_button]
        update_cookie_ammount()
        cps_ammount.config(text=f"cps: {cps}")
        prices[current_button] = round(prices[current_button]*1.2)
        text.config(fg="#000000", text=f"${prices[current_button]}")
        
def check_for_new_button():
    global window
    global multi_cps
    global multi_price

    if cookies >= base_price*multi_price/2:
        create_button(window, base_price*multi_price, multi_cps)
        multi_price*=5
        multi_cps*=4
        

def create_button(window, price, cps):
    global current_row
    global button_n
    global prices

    price_text = Label(window, text=f"${price}", font=sans)
    price_text.grid(column=2, row=current_row)

    prices.append(price)
    current = button_n
    upgrade_button = Button(window, text=f"+{cps} cps", command=lambda: upgrade_cps(cps, price_text, current), font=sans)
    upgrade_button.grid(column=1, row=current_row)

    current_row+=1
    button_n+=1

def change_colors():
    color = (colorchooser.askcolor())[1]
    window.config(bg=color)
    empty_space.config(bg=color)

def exit():
    global loop
    if messagebox.askyesno(title="oh", message="Do you really want to quit? :("):
        loop = False
        window.destroy()

window = Tk()
window.geometry("430x300")
sans = font.Font(window, family="Comic Sans MS")

cps_ammount = Label(window, text=f"cps: {cps}", font=sans)
cps_ammount.grid(column=2, row=1)

cookie_ammount = Label(window, text=f"cookies: {cookies}", font=sans)
cookie_ammount.grid(column=1, row=1)

empty_space = Label(window, padx=100)
empty_space.grid(column=3, row=1)

color_button = Button(window, text="color", command=change_colors, padx=16, font=sans)
color_button.grid(column=4, row=1)

cookie_button = Button(window, text="get cookie", command=get_cookie, font=sans)
cookie_button.grid(column=1, row=2)

window.protocol("WM_DELETE_WINDOW", exit)

window.after(0, get_cps())
while loop is True:
    window.update_idletasks()
    window.update()